apiVersion: v1
kind: Service
metadata: # kpt-merge: example/backstage
  name: backstage
  namespace: example
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|example|backstage'
spec:
  ports:
  - name: http
    port: 7007
    targetPort: http
  selector:
    app.kubernetes.io/name: backstage
